<div style="font-family:Segoe UI,Arial,sans-serif;max-width:820px;margin:auto;color:#1f2937">
@if ($alert->state == 0)
<div style="background:#ecfdf5;border-left:7px solid #059669;padding:18px"><div style="font-size:23px;font-weight:700">🟢 Tæki komið aftur</div><div style="margin-top:6px"><strong>{{ $alert->hostname }}</strong> svarar aftur.</div></div>
<table style="border-collapse:collapse;width:100%;margin-top:16px"><tr><td style="padding:8px;font-weight:600;width:190px">Tæki</td><td>{{ $alert->hostname }}</td></tr><tr style="background:#f3f4f6"><td style="padding:8px;font-weight:600">IP</td><td>{{ $alert->ip }}</td></tr><tr><td style="padding:8px;font-weight:600">Staðsetning</td><td>{{ $alert->location ?? 'Óskráð' }}</td></tr><tr style="background:#f3f4f6"><td style="padding:8px;font-weight:600">Atvik varði</td><td><strong>{{ $alert->elapsed }}</strong></td></tr></table>
@else
<div style="background:#fef2f2;border-left:7px solid #dc2626;padding:18px"><div style="font-size:23px;font-weight:700">🔴 {{ $alert->name }}</div><div style="margin-top:6px">Vandamál greint á <strong>{{ $alert->hostname }}</strong>.</div></div>
<table style="border-collapse:collapse;width:100%;margin-top:16px"><tr><td style="padding:8px;font-weight:600;width:190px">Tæki</td><td>{{ $alert->hostname }}</td></tr><tr style="background:#f3f4f6"><td style="padding:8px;font-weight:600">IP</td><td>{{ $alert->ip }}</td></tr><tr><td style="padding:8px;font-weight:600">Staðsetning</td><td>{{ $alert->location ?? 'Óskráð' }}</td></tr><tr style="background:#f3f4f6"><td style="padding:8px;font-weight:600">Alvarleiki</td><td>{{ strtoupper($alert->severity) }}</td></tr></table>
@if ($alert->faults)<div style="margin-top:16px;font-weight:700">Nánari gögn</div>@foreach ($alert->faults as $value)<div style="padding:9px;margin-top:6px;background:#f9fafb;border:1px solid #e5e7eb">Uptime: {{ $value['uptime'] ?? 'óþekkt' }} · Staða: {{ $value['status'] ?? 'óþekkt' }}</div>@endforeach @endif
@endif
<div style="margin-top:22px;padding-top:12px;border-top:1px solid #d1d5db;font-size:12px;color:#6b7280">LibreNMS · Regla: {{ $alert->name }} · Alert ID: {{ $alert->uid }} · {{ $alert->timestamp }}</div></div>
