<div style="font-family:Segoe UI,Arial,sans-serif;max-width:820px;margin:auto;color:#1f2937">
@if ($alert->state == 0)
<div style="background:#ecfdf5;border-left:7px solid #059669;padding:18px"><div style="font-size:23px;font-weight:700">🟢 Interface komið aftur</div><div style="margin-top:6px"><strong>{{ $alert->hostname }}</strong> er ekki lengur í alert-stöðu.</div></div><div style="margin-top:14px">Atvik varði: <strong>{{ $alert->elapsed }}</strong></div>
@else
<div style="background:#fef2f2;border-left:7px solid #dc2626;padding:18px"><div style="font-size:23px;font-weight:700">🔴 {{ $alert->name }}</div><div style="margin-top:6px">Mikilvægt interface á <strong>{{ $alert->hostname }}</strong> þarfnast athugunar.</div></div>
<table style="border-collapse:collapse;width:100%;margin-top:16px;border:1px solid #d1d5db"><thead><tr style="background:#111827;color:white"><th style="padding:9px;text-align:left">Interface</th><th style="padding:9px;text-align:left">Lýsing</th><th style="padding:9px;text-align:left">Admin</th><th style="padding:9px;text-align:left">Oper</th></tr></thead><tbody>@foreach ($alert->faults as $value)<tr><td style="padding:9px;border-top:1px solid #d1d5db"><strong>{{ $value['ifName'] ?? $value['ifDescr'] ?? 'Óþekkt' }}</strong></td><td style="padding:9px;border-top:1px solid #d1d5db">{{ $value['ifAlias'] ?? 'Engin lýsing' }}</td><td style="padding:9px;border-top:1px solid #d1d5db">{{ $value['ifAdminStatus'] ?? 'Óþekkt' }}</td><td style="padding:9px;border-top:1px solid #d1d5db">{{ $value['ifOperStatus'] ?? 'Óþekkt' }}</td></tr>@endforeach</tbody></table>
<div style="background:#fffbeb;padding:12px;margin-top:15px">Athuga port, ljós/SFP, port-channel og logg. Reglan um port niður vaktar aðeins <strong>[ALERT]</strong> í ifAlias.</div>
@endif
<div style="margin-top:22px;padding-top:12px;border-top:1px solid #d1d5db;font-size:12px;color:#6b7280">LibreNMS · Regla: {{ $alert->name }} · Alert ID: {{ $alert->uid }} · {{ $alert->timestamp }}</div></div>
