<div style="font-family:Segoe UI,Arial,sans-serif;max-width:820px;margin:auto;color:#1f2937">
@if ($alert->state == 0)
<div style="background:#ecfdf5;border-left:7px solid #059669;padding:18px"><div style="font-size:23px;font-weight:700">🟢 Ljósmerki aftur innan marka</div><div style="margin-top:6px">Optical sensor á <strong>{{ $alert->hostname }}</strong> hefur jafnað sig. Atvik varði {{ $alert->elapsed }}.</div></div>
@else
<div style="background:#fef2f2;border-left:7px solid #dc2626;padding:18px"><div style="font-size:23px;font-weight:700">🔴 Optical RX/TX utan marka</div><div style="margin-top:6px">DOM/DDM ljósbreyta á <strong>{{ $alert->hostname }}</strong> er utan alarm-marka.</div></div>
<table style="border-collapse:collapse;width:100%;margin-top:16px;border:1px solid #d1d5db"><thead><tr style="background:#111827;color:white"><th style="padding:9px;text-align:left">Mæling</th><th style="padding:9px;text-align:left">Nú</th><th style="padding:9px;text-align:left">Low alarm</th><th style="padding:9px;text-align:left">High alarm</th></tr></thead><tbody>@foreach ($alert->faults as $value)<tr><td style="padding:9px;border-top:1px solid #d1d5db"><strong>{{ $value['sensor_descr'] ?? 'Optical sensor' }}</strong></td><td style="padding:9px;border-top:1px solid #d1d5db">{{ $value['sensor_current'] ?? 'Óþekkt' }} dBm</td><td style="padding:9px;border-top:1px solid #d1d5db">{{ $value['sensor_limit_low'] ?? '-' }} dBm</td><td style="padding:9px;border-top:1px solid #d1d5db">{{ $value['sensor_limit'] ?? '-' }} dBm</td></tr>@endforeach</tbody></table>
<div style="background:#fffbeb;padding:12px;margin-top:15px">Mjög lágt RX, t.d. -40 dBm, bendir oft til að ekkert ljós berist. Athuga ljósleiðara, tengi, TX/RX pörun, SFP og hinn endann.</div>
@endif
<div style="margin-top:22px;padding-top:12px;border-top:1px solid #d1d5db;font-size:12px;color:#6b7280">LibreNMS · Regla: {{ $alert->name }} · Alert ID: {{ $alert->uid }} · {{ $alert->timestamp }}</div></div>
